# docker-compose.yml

version: '3'

services:
  app:
    image: mcr.microsoft.com/devcontainers/python:0-3.11-bullseye
    restart: always
    ports:
      - 8000:8000
    depends_on:
      - elasticsearch
      - gorbird
    command:
      - pip install -r requirements.txt
      - python manage.py makemigrations
      - python manage.py migrate
      - python manage.py runserver

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.1
    environment:
      - authentication.enabled=false
      - discovery.type=single-node
      - xpack.security.enabled=false

  gorbird:
    container_name: grobid
    image: lfoppiano/grobid:0.8.0
    environment:
      - JAVA_OPTS=-Xmx2G
      - JAVA_XMX=4G
      - JAVA_XMS=2G
      - discovery.type=single-node