# docker-compose.yml

version: '3'

volumes:
  data:
    driver: local

services:
  app:
    image: mcr.microsoft.com/devcontainers/universal:2.6.0-focal
    ports:
      - 8000:8000

    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    depends_on:
      - elasticsearch
      - grobid

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    ports:
      - 9200:9200
    environment:
      - authentication.enabled=false
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - "ES_JAVA_OPTS=-Xms2G -Xmx2G"
      - node.name=elasticsearch
      - discovery.type=single-node
      - ES_PORT=127.0.0.1:9200
      - ELASTIC_PASSWORD=elastictest
    volumes:
      - data:/usr/share/elasticsearch/data 
  grobid:
    image: lfoppiano/grobid:0.8.0
    ports:
      - 8070:8070
    environment:
      - JAVA_XMX=4G
      - JAVA_XMS=2G
