# docker-compose.yml

version: '3'

services:
  app:
    container_name: app
    image: mcr.microsoft.com/devcontainers/python:0-3.11-bullseye
    ports:
      - 8000:8000

    volumes:
      - ..:/workspace:cached

    command: sleep infinity
    depends_on:
      - elasticsearch
      - gorbird

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    ports:
      - 9200:9200
    environment:
      - authentication.enabled=false
      - xpack.security.enabled=false
      - discovery.type=single-node
      - xpack.ml.enabled=false
      - "ES_JAVA_OPTS=-Xms2G -Xmx2G"

  gorbird:
    container_name: grobid
    ports:
      - 8070:8070
    image: lfoppiano/grobid:0.8.0
    environment:
      - JAVA_XMX=4G
      - JAVA_XMS=2G